FROM pmoneda/python:latest

WORKDIR /app
COPY . .
ENV POSTGRES_HOST postgres
ENV POSTGRES_USER postgres

RUN pip install -r requirements.txt
RUN pip install gunicorn

ARG port={{port}}
ENV port=${port:-8000}
EXPOSE $port
ENTRYPOINT python main.py && gunicorn -b 0.0.0.0:$port api.server:app
