FROM pmoneda/python:latest

WORKDIR /app
COPY . .
ENV POSTGRES_HOST postgres
ENV POSTGRES_USER postgres

RUN pip install -r requirements.txt

ENV PORT={{port}}

EXPOSE {{port}}
ENTRYPOINT ["python", "main.py"]